### ISSUE TITLE
Any plans for 1.0?

### ISSUE THREAD

**Issue by kbwatts** [googlearchive/swipeable-card#8]
I'm working on porting this to 1.0 but having a few issues. Has anyone tried this yet with luck or failure they wish to share?

**Comment by kbwatts** [comment]
Nevermind, I got it working (thanks to @padster): https://github.com/kbwatts/swipeable-card - can contribute it back to the master branch if there's any interest.

(still need to fix disableSwipe)

**Comment by notwaldorf** [comment]
You can follow https://github.com/PolymerElements/paper-card/issues/14 for updates but the TL DR is: we will make an `iron-swipeable-container` that will basically make all of its children swipeable, regardless of whether they're cards or not. I have the PR almost ready, so look for it by the end of the week :)

**Comment by kbwatts** [comment]
@notwaldorf Awesome! I'll keep my eyes peeled :eyes: Thanks :)
